### ISSUE TITLE
Can't resume training

### ISSUE THREAD

**Issue by lendrick** [Tetratrio/stylegan2_pytorch#10]
The training script is failing when I try to resume training on my network.  Any idea what's causing this?

[kwargs.json.txt](https://github.com/Tetratrio/stylegan2_pytorch/files/5099921/kwargs.json.txt)

[512.yaml.txt](https://github.com/Tetratrio/stylegan2_pytorch/files/5099925/512.yaml.txt)

(pytorch) D:\AI\sg2\stylegan2_pytorch>python run_training.py 512.yaml --gpu 1 --resume
C:\Users\Bart\anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Bart\anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Bart\anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Bart\anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Bart\anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Bart\anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "run_training.py", line 975, in <module>
    main()
  File "run_training.py", line 970, in main
    run(args)
  File "run_training.py", line 938, in run
    trainer = get_trainer(args)
  File "run_training.py", line 813, in get_trainer
    tensorboard_log_dir=args.tensorboard_log_dir
  File "D:\AI\sg2\stylegan2_pytorch\stylegan2\train.py", line 882, in load_checkpoint
    state_dict = torch.load(fpath, map_location=torch.device(loaded_kwargs['device']))
TypeError: Device() received an invalid combination of arguments - got (list), but expected one of:
 * (torch.device device)
      didn't match because some of the arguments have invalid types: (←[31;1mlist←[0m)
 * (str type, int index)

**Comment by adriansahlman** [comment]
Hey, I think I found the bug and have pushed a fix. Try to pull the latest changes and resume training again. Tell me if you are successful or not!

**Comment by lendrick** [comment]
That fixed the issue!  Thanks for being so responsive. :)

**Comment by adriansahlman** [comment]
No problem, glad you found the code useful! :)
