### ISSUE TITLE
Channels option in training.

### ISSUE THREAD

**Issue by Michi-123** [Tetratrio/stylegan2_pytorch#13]
I want to train 256 pixels images, and trained with this options:  
`!python run_training.py --channels [32, 32, 64, 128, 256, 256, 256, 256, 256] --data_dir images`
but got error message bellow.
`... some messages ... 
 run_training.py: error: argument --channels: invalid int value: '[32,'`

Thanks!

**Comment by adriansahlman** [comment]
Hey!

Command line arguments where there are multiple values for an option should be specified as
`--channels 32 32 64 128 256 256 256 256 256 --data_dir ...`
Also if you want to train with images of size 256x256 you need to reduce the number of channel values. The size of the output image will be 2 ^ (n_channels + 1). If the argument `--base_shape` is not changed that is.
`--channels 64 128 256 256 256 256 256` should produce images of size 256x256.

Hope this helps!

**Comment by Michi-123** [comment]
Thank you very much. 
But I'm not sure about this option.
`--base_shape`

**Comment by Michi-123** [comment]
[base_shape=(4,4)](https://github.com/Tetratrio/stylegan2_pytorch/blob/67b7a5f6e96371f279e179c158710656c73f18be/stylegan2/models.py#L723
)

I got it. This is constant layer, isn't it!
It works!  Thanks a lot.

**Comment by adriansahlman** [comment]
Yea, that is the constant layer. You can change the size of it the same way as you pick channels, i.e. `--base_shape 4 4`!
