### ISSUE TITLE
How to convert the G.pth to ONNX

### ISSUE THREAD

**Issue by wodsoe** [Tetratrio/stylegan2_pytorch#22]
How to convert the G.pth to ONNX？
Thank you!

**Comment by adriansahlman** [comment]
Hey, sorry for the late reply. I think you would have to write your own code and import the project, load the model and then follow the steps in https://pytorch.org/docs/master/onnx.html

```python
import stylegan2

model = stylegan2.models.load('G.pth')
dummy_input = torch.randn(1, 512)
torch.onnx.export(model, dummy_input, "G.onnx", verbose=True, input_names=['latent'], output_names=['output'])
```
Im not sure if this is correct, but it should be something like that I think

**Comment by wodsoe** [comment]
Thank you!
