### ISSUE TITLE
this weight is only about 8k ?

### ISSUE THREAD

**Issue by Johnson-yue** [Tetratrio/stylegan2_pytorch#4]
https://github.com/Tetratrio/stylegan2_pytorch/blob/4440fd660d432e46cbe9ee352b8e9cdc3fa6a242/stylegan2/external_models/lpips.py#L36-L37

**Comment by Johnson-yue** [comment]
I download this local file by VPN it is only 8K byte？

**Comment by adriansahlman** [comment]
Hey!

Yes that is correct, for me it is 7.1 KB.

It is not the weights for VGG conv layers, that is downloaded when loading the pretrained VGG in Pytorch.

The weights you downloaded are used to scale the similarity score for each layer's features before combining the score into the final score!

Hope this helps
