### ISSUE TITLE
a small bug

### ISSUE THREAD

**Issue by Johnson-yue** [Tetratrio/stylegan2_pytorch#5]
https://github.com/Tetratrio/stylegan2_pytorch/blob/4440fd660d432e46cbe9ee352b8e9cdc3fa6a242/stylegan2/modules.py#L1426

it should be `latents.unsqueeze(1)` ? not `latent` ?

**Comment by adriansahlman** [comment]
Hey,

Nice catch! You are right!
I pushed a fix. Thanks a lot for sharing!
