### ISSUE TITLE
How to use pretrained network for resume training?

### ISSUE THREAD

**Issue by Mehrab-Tanjim** [Tetratrio/stylegan2_pytorch#9]
The convert script downloads pretrained network and only generates three files D, G, and Gs. But it seems to be able to resume from a previous checkpoint, D_opt, G_opt and kwargs are required. So, I was wondering how one can resume pretraining using this?

**Comment by adriansahlman** [comment]
Hey, that feature is actually missing. I will try to add it today!

**Comment by Mehrab-Tanjim** [comment]
That sounds great! Looking forward to it!

**Comment by adriansahlman** [comment]
Hey, I added --g_model and --d_model as arguments to the training script. Specify the model weight file (the one that has been converted to pytorch) with these arguments

**Comment by Mehrab-Tanjim** [comment]
Much appreciated! One issue I am facing is that when I load both G and D from the pre-trained model for FFHQ, it faces CUDA out-of-memory issues (even with smaller batch sizes like 16 and 4 Tesla V100 GPUs). I'm not sure if it was supposed to happen since previously it was running just fine.  One thing I've noticed is that when I only load G and let it train D from scratch it runs smoothly. However, it did not quite produce the same result as the official model did. Anyways, this is a great port to PyTorch, and hopefully, we can make it even better.

**Comment by adriansahlman** [comment]
Sounds weird that it runs out of memory only when using the pretrained model, no idea why.

This was a fun side project I did during winter vacation and it was a long time since I worked on it so my memory of the implementation is not too fresh. But as far as I can remember I tried to replicate the tensorflow repo as closely as possible. If you find any way to make it perform similarly I would love to hear it!

One difference for this implementation is that the filter function is written in pure pytorch, not in C++ cuda like it is in the official repo (I wanted to support 1D and 3D data as well as 2D when I made the repo so I could not just use their cuda code).

**Comment by Mehrab-Tanjim** [comment]
Yes, for me, for some reason, it went out of memory after 16 steps during backprop. If I can figure out the specific issues, and fix them, I will let you know. Regarding getting the results, maybe training 'D' from scratch was the culprit. Btw, as a 'fun' side project, surely you have done a lot!

**Comment by adriansahlman** [comment]
Thanks, however as usual when looking back at code you wrote a long time ago you always feel like it could have been done so much better hehe.

I never had access to more than 11GB of ram so I could not try running it with 1024x1024 without removing the batch std layer and reducing the batch size to < 4. I did run it for a long time on 512x512 and did not see a memory increase during that time so it is probably not some kind of memory leak at least.

I ran into an issue of OOM recently when training multiple models (similar to this repo, where each model is updated in a separate iteration) and it seemed like Pytorch did not mark the used memory as free quick enough when the next forward pass was not the same as the previous one. So by calling torch.cuda.empty_cache() between each iteration I could solve the issue.

**Comment by Mehrab-Tanjim** [comment]
Sounds like a solid idea, let me try this.

**Comment by Mehrab-Tanjim** [comment]
So, the out of memory happens during loss.backwards() in one of the GPUs and I tried with emptying the cache, but it did not help. Somebody mentions in PyTorch, they have similar problems, and emptying cache does not always work: https://discuss.pytorch.org/t/runtimeerror-cuda-out-of-memory-during-loss-backward/53450/6. He got around it by using a different architecture, which, unfortunately, in our case, we cannot afford to do :(. I will keep trying some other techniques, and if I am able to solve the problem, I will do a pull request.

**Comment by adriansahlman** [comment]
Hey, great detective work finding the issue! :D It's a bit weird because I was under the impression that the computation graph is removed after a backward call (unless using `retain_graph=True`) but there seems to be something a bit weird when training multiple different models at the same time with Pytorch.

Thanks a lot for fixing it! Im guessing that you still need 16gb ram for 1024x1024 (at the lowest batch size of 4 per GPU)?

**Comment by Mehrab-Tanjim** [comment]
Yes, I do. Btw using loss.item() may have some undesired effects. Like after training for a day, all the generated images are black for some reason, which should not happen. It might be my data specific issue, can you kindly test and then keep/revert the changes?

**Comment by adriansahlman** [comment]
Hey, I took a look and it seems like the _backward() functions return value (which is what has changed to loss.item()) is only used for logging purposes!

I dont know why the outputted images are black, maybe the training is unstable and collapsed. Did the gradient norm do any weird things during training? Like shoot up really high or go really low? Or did the generated images slowly go darker or just suddenly turn completely dark?

**Comment by Mehrab-Tanjim** [comment]
yes, you are right, there were multiple spikes, and I think training collapsed. It is weird because the official version did not collapse, and I was under the impression that it would not collapse in our case as well. Do you know any good technique to ensure that the training does not collapse?

**Comment by adriansahlman** [comment]
As far as I can remember the most stabilizing thing for me was the regularization and low learning rates. I never had the opportunity to try out 1024x1024 but had it training in a very stable fashion at 512x512, even when I resumed the training. Although this was back in January and I dont remember the exact settings :/

**Comment by adriansahlman** [comment]
Work really started picking up in the beginning of this year so I had no more spare time. I wish I had more time so I could also test the GAN for 1D and 3D data (as it should already be supported by this code). Would be pretty cool to be able to generate MRI scans.
